events {}

http {
    server {
        listen 80;

        # Serve static files from /usr/share/nginx/html
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
