name: Test Setup Java

on:
  workflow_dispatch:

jobs:
  test-setup-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
